# Generated by Django 4.2.1 on 2023-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
