# Generated by Django 4.2.1 on 2023-05-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userlogin_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='MyUser',
        ),
    ]
